### ISSUE TITLE
how is this diff than icepick?

### ISSUE THREAD

**Issue by sirvon** [OneCodeLabs/reminder#12]
Thanks for the lib.

Just wondering how is this different from icepick and the other bundle saving/restoring mechanisms?

Thanks again!

**Comment by goodengineer** [comment]
Hey @sirvon! You're welcome, and thanks for checking out the lib! :)

icepick makes it easy to use the instance state feature android provides.

reminder saves your data cross sessions, meaning you will have saved data even if you close your application and open it again (this doesn't happen with instance state). Also, reminder tells you how old the saved data is in order to decide if you can still use it (and save a request to your API) or if it's too old and it can't be used.

reminder allows showing data even when there's no internet available, like facebook or twitter do, which icepick doesn't :)

Sorry for the delay!
